### PR TITLE
Require a well-formed rootURL

### PR DESCRIPTION
**Pull request by djmitche**
I decided to just require this to be well-formatted, rather than silently normalizing it.

### CODE REVIEW

**Comment by djmitche** [comment]
We had considered adding it in tc-lib-urls, but it risks breaking existing functionality there.  Currently, URL generation is lenient and works either with or without a trailing `/`.

This does fix a case where a worker was misconfigured and thus TASKCLUSTER_ROOT_URL in the task execution had a trailing `/`.  A script within the task concatenated this value, creating a URL with a `//` in it.  So, this would prevent that particular misconfiguration.

I suppose we could do this in tc-lib-urls and just accept the bustage?

**Comment by djmitche** [comment]
In fact, we *test* that we are lenient with respect to rootURLs with trailing `/` in tc-lib-urls.

@petemoore, what if we added a `normalizeRootURL` function to tc-lib-urls, and called that here?  Then Taskcluster components could be [lenient in what they accept, and strict in what they produce](https://en.wikipedia.org/wiki/Robustness_principle).

**Comment by petemoore** [comment]
That sounds like a good idea. I like your idea. Many thanks!

**Comment by djmitche** [comment]
https://github.com/taskcluster/taskcluster-lib-urls/pull/31

**Pull request merged**
